[package]
name = "zeronet"
version = "0.1.0"
authors = ["canewsin <canews.in@gmail.com>"]
edition = "2021"


[dependencies]
tokio = { version = "1.17.0", features = ["full"] }
zeronet_cryptography = { path = "./zeronet_cryptography" }
zeronet_protocol = { path = "./zeronet_protocol", features = ["tor", "i2p"] }
zerucontent = { path = "./zerucontent"}
futures = "0.3.5"
sha2 = "0.10.2"
serde = { version = "1.0.110", features = ["derive"] }
serde_bytes = "0.11.5"
serde_json = "1.0.55"
rmp-serde = "1.0.0"
rmp = "0.8.10"
log = "0.4.14"
sha1 = "0.10.1"
chrono = "0.4.19"
lazy_static = "1.4.0"
clap = "3.1.5"
num-bigint = "0.4"
rand = "0.8.4"
bitcoin = "0.27.1"
bincode = "1.3.3"
async-trait = "0.1.52"
